# Generated by Django 3.1.6 on 2021-02-09 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 15, 56, 55, 144292, tzinfo=utc)),
        ),
    ]
