# Generated by Django 3.1.6 on 2021-02-10 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0002_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date',
        ),
        migrations.AddField(
            model_name='login',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
