# Generated by Django 3.1.6 on 2021-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0003_auto_20210210_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
