# Generated by Django 3.1.6 on 2021-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0004_registrationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='address',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='company',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='employees',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='reg_no',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='sector',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='turnover',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
