# Generated by Django 3.1.6 on 2021-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0005_auto_20210212_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='country',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
