# Generated by Django 3.1.6 on 2021-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0006_registrationdata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='air_travel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='automobile',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='public_transport',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='waste',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='water',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
