# Generated by Django 3.1.6 on 2021-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0007_auto_20210222_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='air_travel',
            new_name='electricity_amount',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='automobile',
            new_name='electricity_gas',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='electricity',
            new_name='electricity_heating',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='public_transport',
            new_name='electricity_provider',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='travel_accommodation',
            new_name='electricity_renewable',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='waste',
            new_name='electricity_type',
        ),
        migrations.RenameField(
            model_name='registrationdata',
            old_name='water',
            new_name='office_utilities_desktop',
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_utilities_laptop',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_battery',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_bio',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_glass',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_hardware',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_paper',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_plastic',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_water',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_airbnb',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_hostel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_hotel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_motel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_air_travel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_automobile_commute',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_automobile_mileage',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_bus',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_coach',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_int_train',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_subway',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_taxi',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_train',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_tram',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
