# Generated by Django 3.1.6 on 2021-03-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0008_auto_20210320_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='test_field',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
