# Generated by Django 3.1.6 on 2021-03-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0011_auto_20210321_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbondata',
            options={'ordering': ['test_field']},
        ),
        migrations.RenameField(
            model_name='carbondata',
            old_name='electricity_amount',
            new_name='test_field',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='electricity_gas',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='electricity_heating',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='electricity_provider',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='electricity_renewable',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='electricity_type',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_utilities_desktop',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_utilities_laptop',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_battery',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_bio',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_glass',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_hardware',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_paper',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_plastic',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_water',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_accommodation_airbnb',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_accommodation_hostel',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_accommodation_hotel',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_accommodation_motel',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_air_travel',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_automobile_commute',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_automobile_mileage',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_bus',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_coach',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_int_train',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_subway',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_taxi',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_train',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_tram',
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity_amount',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity_gas',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity_heating',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity_provider',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity_renewable',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='electricity_type',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_utilities_desktop',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_utilities_laptop',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_battery',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_bio',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_glass',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_hardware',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_paper',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_waste_plastic',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='office_water',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_airbnb',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_hostel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_hotel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_accommodation_motel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_air_travel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_automobile_commute',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_automobile_mileage',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_bus',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_coach',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_int_train',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_subway',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_taxi',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_train',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='travel_tram',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
