# Generated by Django 3.1.6 on 2021-03-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0014_auto_20210322_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_accommodation_airbnb',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_accommodation_hostel',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_accommodation_hotel',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_accommodation_motel',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_air_travel',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_automobile_commute',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_automobile_mileage',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_bus',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_coach',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_int_train',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_subway',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_taxi',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_train',
        ),
        migrations.RemoveField(
            model_name='registrationdata',
            name='travel_tram',
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_accommodation_airbnb',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_accommodation_hostel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_accommodation_hotel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_accommodation_motel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_air_travel',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_automobile_commute',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_automobile_mileage',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_bus',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_coach',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_int_train',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_subway',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_taxi',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_train',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carbondata',
            name='travel_tram',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
