# Generated by Django 3.1.6 on 2021-03-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0016_auto_20210322_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbondata',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='test_field',
        ),
    ]
