# Generated by Django 3.1.6 on 2021-03-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogInApp', '0017_auto_20210322_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogIn',
        ),
    ]
